name: 🌠 JSON to env
description: 🌠 Take a JSON object as an input and set every entries as environment variable
inputs:
  json:
    description: '(Required) JSON entries to set as environment variable'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo '${{ inputs.json }}' | jq -r 'to_entries[] | select(.key | startswith("APP_")) | "\(.key)=\(.value)"' >> $GITHUB_ENV
      shell: bash

