name: ▶️ Merge feature
on:
  push:
jobs:
  integrate-kotlin:
    name: ▶️ Integrate kotlin
    runs-on: ubuntu-22.04
    steps:
      - name: ℹ️ Print
        run: echo "::notice::▶️ Integrate kotlin"
      - name: ℹ️ Print
        run: echo "::notice::▶️ Integrate kotlin"
      - name: ℹ️ Print
        run: echo "::notice::▶️ Integrate kotlin"
