name: ▶️ Integrate feature
on:
  push:
jobs:
  integrate-kotlin:
    name: ▶️ Integrate kotlin
    uses: VelcoTech/github-workflows/.github/workflows/integrate-kotlin.yml@feature/daws-27 # TODO UPDATE GIT REF
    with:
      java-version: '17'
