name: ⭐ Use composites actions
on:
  push:
jobs:
  goodbye:
    name: Goodbye
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: .github/actions/goodbye
        with:
          who-to-greet: 'Mona the Octocat'
