name: ⭐ Create release
on:
  push:
permissions:
  contents: write
  pull-requests: write
jobs:
  merge:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: VelcoTech/gitflow-sample/.github/actions/json-to-env@develop
        with:
          json: '{"a": "a"}'
      - uses: VelcoTech/gitflow-sample/.github/actions/json-to-env@develop
        with:
          json: '{"b": "b"}'
      - run: printenv
